#!/usr/bin/env python3
"""
ManeYantra Secrets Setup Helper
Generates secure secrets and creates .env file
"""

import os
import secrets
import string
from pathlib import Path


def generate_password(length=32, include_special=True):
    """Generate a secure random password"""
    if include_special:
        alphabet = string.ascii_letters + string.digits + "!@#$%^&*()-_=+[]{}|;:,.<>?"
    else:
        alphabet = string.ascii_letters + string.digits

    password = ''.join(secrets.choice(alphabet) for _ in range(length))
    return password


def generate_secret_key(length=64):
    """Generate a secure secret key (hex)"""
    return secrets.token_hex(length // 2)


def create_env_file(force=False):
    """Create .env file with secure secrets"""
    project_root = Path(__file__).parent.parent
    env_file = project_root / ".env"
    env_example = project_root / ".env.example"

    # Check if .env already exists
    if env_file.exists() and not force:
        print(f"⚠️  .env file already exists at {env_file}")
        response = input("Do you want to overwrite it? (yes/no): ").lower()
        if response not in ['yes', 'y']:
            print("❌ Aborted. Keeping existing .env file.")
            return False

    # Generate secure credentials
    print("🔐 Generating secure credentials...")
    rabbitmq_user = "maneyantra"
    rabbitmq_password = generate_password(32, include_special=False)
    secret_key = generate_secret_key(64)

    # Read example file if exists
    if env_example.exists():
        with open(env_example, 'r') as f:
            template = f.read()
    else:
        template = ""

    # Create .env content
    env_content = f"""# ManeYantra Environment Configuration
# Generated by setup_secrets.py
# ⚠️  DO NOT COMMIT THIS FILE TO VERSION CONTROL

# RabbitMQ Broker Configuration
RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
RABBITMQ_USERNAME={rabbitmq_user}
RABBITMQ_PASSWORD={rabbitmq_password}
RABBITMQ_VHOST=/

# Secret Key (for encryption, tokens, etc.)
SECRET_KEY={secret_key}

# Eufy Credentials (Optional - fill in if using Eufy devices)
EUFY_USERNAME=
EUFY_PASSWORD=
EUFY_COUNTRY=US

# TP-Link Kasa Configuration (Optional)
# TPLINK_USERNAME=
# TPLINK_PASSWORD=

# System Configuration
LOG_LEVEL=INFO
DATA_DIR=./data
LOGS_DIR=./logs

# Development/Production Mode
ENVIRONMENT=production
"""

    # Write .env file
    with open(env_file, 'w') as f:
        f.write(env_content)

    # Set secure permissions (readable only by owner)
    os.chmod(env_file, 0o600)

    print(f"✅ Created .env file at {env_file}")
    print(f"🔒 File permissions set to 600 (owner read/write only)")
    print()
    print("📋 Generated Credentials:")
    print(f"   RabbitMQ Username: {rabbitmq_user}")
    print(f"   RabbitMQ Password: {rabbitmq_password}")
    print(f"   Secret Key: {secret_key[:16]}... (truncated)")
    print()
    print("⚠️  IMPORTANT: Save these credentials securely!")
    print()

    # Create docker-compose override file
    create_docker_override(rabbitmq_user, rabbitmq_password)

    # Prompt for optional credentials (only in interactive mode)
    import sys
    if sys.stdin.isatty():
        print("📝 Optional: Enter device credentials (press Enter to skip)")
        print()

        try:
            eufy_user = input("Eufy Username (email): ").strip()
            if eufy_user:
                eufy_pass = input("Eufy Password: ").strip()
                update_env_value(env_file, "EUFY_USERNAME", eufy_user)
                update_env_value(env_file, "EUFY_PASSWORD", eufy_pass)
                print("✅ Eufy credentials added")
        except (EOFError, KeyboardInterrupt):
            print("\n⏭️  Skipping optional credentials")

    print()
    print("✨ Setup complete! You can now run: docker compose up -d")
    print("💡 Edit .env to add device credentials (Eufy, TP-Link) later if needed")

    return True


def create_docker_override(rabbitmq_user, rabbitmq_password):
    """Create docker-compose.override.yml with secure credentials"""
    project_root = Path(__file__).parent.parent
    override_file = project_root / "docker-compose.override.yml"

    override_content = f"""# Docker Compose Override - Generated Secrets
# This file is automatically generated by setup_secrets.py
# ⚠️  DO NOT COMMIT THIS FILE TO VERSION CONTROL

version: '3.8'

services:
  rabbitmq:
    environment:
      RABBITMQ_DEFAULT_USER: {rabbitmq_user}
      RABBITMQ_DEFAULT_PASS: {rabbitmq_password}

  maneyantra:
    environment:
      RABBITMQ_USERNAME: {rabbitmq_user}
      RABBITMQ_PASSWORD: {rabbitmq_password}
"""

    with open(override_file, 'w') as f:
        f.write(override_content)

    os.chmod(override_file, 0o600)
    print(f"✅ Created docker-compose.override.yml")


def update_env_value(env_file, key, value):
    """Update a specific value in .env file"""
    with open(env_file, 'r') as f:
        lines = f.readlines()

    updated = False
    for i, line in enumerate(lines):
        if line.startswith(f"{key}="):
            lines[i] = f"{key}={value}\n"
            updated = True
            break

    if not updated:
        lines.append(f"{key}={value}\n")

    with open(env_file, 'w') as f:
        f.writelines(lines)


def main():
    """Main entry point"""
    print("=" * 60)
    print("🏠 ManeYantra - Secrets Setup Helper")
    print("=" * 60)
    print()

    import sys
    force = '--force' in sys.argv or '-f' in sys.argv

    create_env_file(force=force)


if __name__ == "__main__":
    main()
